<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php $helper = $this->helper('MGS\Mpanel\Helper\Data') ?>
<?php $header = $helper->getStoreConfig('mgstheme/general/header') ?>
<div class="mobile-text-strip">
<?php echo $this->getLayout()
            ->createBlock('Magento\Cms\Block\Block')
            ->setBlockId('mobile-header-image')
            ->toHtml(); ?>
</div>
<?php 
	$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
	$category = $objectManager->get('Magento\Framework\Registry')->registry('current_category');//get 
    $categoryFactory = $objectManager->get('\Magento\Catalog\Model\CategoryFactory');
 	$baseUrl =  $objectManager->get('Magento\Store\Model\StoreManagerInterface')
            ->getStore()
            ->getBaseUrl();
 	if(isset($category)):
 		/*$parentCategoryObj = $category->getParentCategory($category->getId());
 		if($parentCategoryObj->getName() == 'Designers' || $parentCategoryObj->getUrlKey() == 'designers'):*/
 			$catInfo = $categoryFactory->create()->load($category->getId());
 		 ?>
 		<div class="desinger-style column main col-lg-12 col-md-12 col-sm-12 col-xs-12">
			<div class="brand-info<?php  if(!empty($catInfo->getImageUrl())){ ?> has-desktop-image<?php } ?><?php  if(!empty($catInfo->getGalleryone())){ ?> has-mobile-image<?php } ?>">
				<?php  if(!empty($catInfo->getImageUrl())){ ?>
			        <div class="brand-image desktop-version">
			        <img class="img-responsive" src="<?php echo $baseUrl; ?><?php echo $catInfo->getImageUrl();?>" alt="La Figueretti">
			    	</div>
			    <?php } ?>
			    <?php  if(!empty($catInfo->getGalleryone())){ ?>
			        <div class="brand-image mobile-version">
			        <img class="img-responsive" src="<?php echo $baseUrl; ?><?php echo $catInfo->getGalleryone();?>" alt="La Figueretti">
			    	</div>
			    <?php } ?>	
			        <div class="brand-description">
						<div class="brand-name">
							<?php echo $catInfo->getName(); ?>
						</div>
						<?php if(!empty($catInfo->getDescription())){ ?>
							<span>
								<?php echo strip_tags($catInfo->getDescription()); ?>
							</span>
						<?php } ?>    
			        </div>
			</div>
		</div>
		<?php //endif;
 	endif;
?>

<div class="breadcrumbs <?php if($header == 'header_5') echo 'breadcrumbs-no-bg';?>">
	<div class="container">
		<div class="breadcrumbs-content">
			<!-- <div class="breadcrumbs-title">
				<?php //$objectManager = \Magento\Framework\App\ObjectManager::getInstance(); ?>
				<?php //$fullActionName = $objectManager->get('Magento\Framework\App\Request\Http')->getFullActionName(); ?>
				<?php //if($fullActionName == "catalog_product_view"): ?>
					<span class="h1"><?php //echo __('Product Detail'); ?></span>
				<?php //else: ?>
					<?php //if($crumbs && is_array($crumbs)): ?>
						<?php //foreach ($crumbs as $crumbName => $crumbInfo) : ?>
							<?php //if ($crumbInfo['last']) : ?>
								<h1><?php //echo $block->escapeHtml($crumbInfo['label']) ?></h1>
							<?php //endif ?>
						<?php //endforeach; ?>
					<?php //else: ?>
						<?php //echo $this->getLayout()->createBlock("Magento\Theme\Block\Html\Title")->setTemplate("Magento_Theme::html/title.phtml")->toHtml(); ?>
					<?php //endif ?>
				<?php //endif ?>
			</div> -->
			<?php if ($crumbs && is_array($crumbs)) : ?>
				<ol class="breadcrumb">
					<?php foreach ($crumbs as $crumbName => $crumbInfo) : ?>
						<?php if ($crumbInfo['link']) : ?>
							<li class="item <?php /* @escapeNotVerified */ echo $crumbName ?>">
								<a href="<?php /* @escapeNotVerified */ echo $crumbInfo['link'] ?>" title="<?php echo $block->escapeHtml($crumbInfo['title']) ?>">
									<?php echo $block->escapeHtml($crumbInfo['label']) ?>
								</a>
							</li>
						<?php elseif ($crumbInfo['last']) : ?>
							<li class="active">
								<?php echo $block->escapeHtml($crumbInfo['label']) ?>
							</li>
						<?php else: ?>
							<li class="item">
								<?php echo $block->escapeHtml($crumbInfo['label']) ?>
							</li>
						<?php endif; ?>
					<?php endforeach; ?>
				</ol>
				
			<?php endif ?>
			<?php $fullActionName = $objectManager->get('Magento\Framework\App\Request\Http')->getFullActionName(); ?>
			<?php if($fullActionName == "catalog_category_view"): 
			   $category = $objectManager->get('Magento\Framework\Registry')->registry('current_category')  ?>
				<h1 class="category_name"><?php echo $category->getName(); ?></h1>
			<?php endif ?>
				
		</div>
	</div>
</div>
