<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<div class="block newsletter">
    <div class="content">
        <form class="form subscribe"
            novalidate
            action="<?php /* @escapeNotVerified */ echo $block->getFormActionUrl() ?>"
            method="post"
            data-mage-init='{"validation": {"errorClass": "mage-error"}}'
            id="newsletter-validate-detail-footer">
            <div class="field form-group newsletter">
                <div class="control">
                    <input name="email" type="email" id="newsletter-footer"
                                placeholder="<?php /* @escapeNotVerified */ echo __('Enter Email Address') ?>"
                                data-validate="{required:true, 'validate-email':true}"/>
                </div>
            </div>
            <div class="actions">
                <button class="action subscribe btn btn-secondary" title="<?php /* @escapeNotVerified */ echo __('Subscribe') ?>" type="submit">
                    <span><?php /* @escapeNotVerified */ echo __('Subscribe') ?></span>
                </button>
            </div>
            <div class="subscribe-radio">
                <input type="radio" name="footer_sbscribe" id="women">
                <label for="women">Women</label>
                <input type="radio" name="footer_sbscribe" id="men">
                <label for="men">men</label>
                <input type="radio" name="footer_sbscribe" id="kids">
                <label for="kids">kids</label>
                <input type="radio" name="footer_sbscribe" id="home-deco" required>
                <label for="home-deco">Home Deco</label>
            </div>
        </form>
    </div>
</div>
