<?php
// @codingStandardsIgnoreFile

/** 
 * @var $block \Magento\Catalog\Block\Product\View
 */
?>
<?php $_product = $block->getProduct(); 
$productType = $_product->getTypeID();
if($productType == \Magento\ConfigurableProduct\Model\Product\Type\Configurable::TYPE_CODE):?>
	<!-- Quantity input box -->
	<?php if ($block->shouldRenderQuantity()): ?>
	<div class="field qty">
		<label class="label" for="qty"><span><?php /* @escapeNotVerified */ echo __('Quantity') ?></span></label>
		<div class="control">
			<input type="number"
				   name="qty"
				   id="qty"
				   maxlength="12"
				   value="<?php /* @escapeNotVerified */ echo $block->getProductDefaultQty() * 1 ?>"
				   title="<?php /* @escapeNotVerified */ echo __('Qty') ?>" class="input-text qty"
				   data-validate="<?php echo $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
				   />
			<span class="edit-qty plus fa fa-angle-up" onclick="plusQty('qty')"></span>
			<span class="edit-qty minus fa fa-angle-down" onclick="minusQty('qty')"></span>
		</div>
	</div>
	<?php endif; ?>
<?php endif; ?>	

