<?php
// @codingStandardsIgnoreFile

/** 
 * @var $block \Magento\Catalog\Block\Product\View
 */
$objectManager =  \Magento\Framework\App\ObjectManager::getInstance();
$registry = $objectManager->get('\Magento\Framework\Registry');
$_product = $registry->registry('current_product');

?>
<div class="page-title-wrapper">
	<h1 class="page-header">
		<span class="base" data-ui-id="page-title-wrapper"><?php echo $_product->getName(); ?></span>    
	</h1>
</div>