<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Magento2.Templates.ThisInTemplate

/** @var $block \Magento\Sales\Block\Order\Email\Items */
?>
<?php $_order = $block->getOrder() ?>
<?php if ($_order) : ?>
    <?php $_items = $_order->getAllItems(); ?>
    <table class="email-items" style="width:100%;">
        <thead>
            <tr>
                <th class="item-info" style="text-align:left; border-bottom:1px solid #ddd; font-size: 16px; width:72%; text-align: left; font-weight: bold; color: #1A1818;">
                    <?= $block->escapeHtml(__('Items')) ?>
                </th>
                <th class="item-qty" style="font-size: 16px; border-bottom:1px solid #ddd; text-align: left; font-weight: bold; color: #1A1818;">
                    <?= $block->escapeHtml(__('Qty')) ?>
                </th>
                <th class="item-price" style="font-size: 16px; border-bottom:1px solid #ddd; text-align: left; font-weight: bold; color: #1A1818;">
                    <?= $block->escapeHtml(__('Price')) ?>
                </th>
            </tr>
        </thead>
        <?php foreach ($_items as $_item) : ?>
            <?php if (!$_item->getParentItem()) : ?>
                <tbody>
                    <tr>
                        <td colspan="3">
                            <?= $block->getItemHtml($_item) ?>
                        </td>
                    </tr>
                </tbody>
            <?php endif; ?>
        <?php endforeach; ?>
        <tfoot class="order-totals" style="text-align:left;">
            <tr>
                <td colspan="3">
                    <h2 style="font-size: 16px; font-weight: bold; color: #1A1818; text-align: left;">TOTAL</h2>
                    <?= $block->getChildHtml('order_totals') ?>
                </td>
            </tr>
        </tfoot>
    </table>
    <?php if ($this->helper(\Magento\GiftMessage\Helper\Message::class)
            ->isMessagesAllowed('order', $_order, $_order->getStore())
        && $_order->getGiftMessageId()
    ) : ?>
        <?php $_giftMessage = $this->helper(\Magento\GiftMessage\Helper\Message::class)
            ->getGiftMessage($_order->getGiftMessageId()); ?>
        <?php if ($_giftMessage) : ?>
            <br />
            <table class="message-gift">
                <tr>
                    <td>
                        <h3><?= $block->escapeHtml(__('Gift Message for this Order')) ?></h3>
                        <strong><?= $block->escapeHtml(__('From:')) ?></strong> <?= $block->escapeHtml($_giftMessage->getSender()) ?>
                        <br /><strong><?= $block->escapeHtml(__('To:')) ?></strong> <?= $block->escapeHtml($_giftMessage->getRecipient()) ?>
                        <br /><strong><?= $block->escapeHtml(__('Message:')) ?></strong>
                        <br /><?= $block->escapeHtml($_giftMessage->getMessage()) ?>
                    </td>
                </tr>
            </table>
        <?php endif; ?>
    <?php endif; ?>
<?php endif; ?>
