<?php
$customFieldLabel = __("Phone Numbers");
$customField = "custom_phones";
?>
<div class="field <?= $customField ?> required">
    <label class="label" for="<?= $customField ?>">
        <span><?= $block->escapeHtml($customFieldLabel) ?></span>
    </label>
    <div class="control">
        <input type="text" name="<?= $customField ?>" id="<?= $customField ?>" value=""
               title="<?= $block->escapeHtmlAttr($customFieldLabel) ?>"
               class="input-text" data-validate="{required:true}">
    </div>
</div>