<?php $themeHelper = $this->getThemeHelper(); ?>
<?php $themeSettings = $themeHelper->getThemeSettings(); ?>
<?php $_imagehelper = $this->getImageHelper(); ?>
<?php $lazyLoad = $themeHelper->getStoreConfig('mgstheme/general/lazy_load'); ?>
<?php $baseImage = $this->getViewFileUrl('MGS_Mpanel::images/blank.png'); ?>
<?php $useSlider = $this->getUseSlider(); ?>
<?php $_helper = $this->getCatalogHelperOutput(); ?>
<?php $image = 'category_page_grid'; ?>
<?php $_url_with_color = ''; $_parent_product = []; ?>
<?php $_product = $this->getLoadProduct($this->getProductId()); ?>
<?php 
$_objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$_parent_product = $_objectManager->create('Magento\ConfigurableProduct\Model\ResourceModel\Product\Type\Configurable')->getParentIdsByChild($this->getProductId());
	if(isset($_parent_product[0])){
		$parproduct = $this->getLoadProduct($_parent_product[0]);
		$_url_with_color = $parproduct->getProductUrl()."?color=".$_product->getAttributeText('color');
	}else{
		$_url_with_color = '';
	}
?>
<?php $_productNameStripped = $block->stripTags($_product->getName(), null, true); ?>

<div class="product-item-info" data-container="product-grid">
	
	<?php // Product Top ?>
	<div class="product-top">
	
		<?php // Product Image ?>
		<?php $size = $themeHelper->getImageSize($this->getRatio()); ?>
		<?php $productImage = $_imagehelper->init($_product, $image)->resize($size['width'], $size['height'])->getUrl(); ?>
		<?php 
			if(!$lazyLoad){
				$baseImage = $productImage;
			}
		?>
		<?php if ($_url_with_color){ ?>
		<a href="<?php  echo $_url_with_color ?>" class="product photo product-item-photo" tabindex="-1">
		<?php }else{ ?>
		<a href="<?php  echo $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
		<?php } ?>
			<img src="<?php echo $baseImage ?>" alt="<?php echo $_productNameStripped ?>" data-<?php if($useSlider): ?>src<?php else: ?>original<?php endif ?>="<?php echo $productImage ?>" class="img-responsive product-image-photo img-thumbnail<?php if($lazyLoad): ?> <?php if($useSlider): ?>owl-<?php endif ?>lazy<?php endif ?>" />
		</a>
		
		<?php // Product Label ?>
		<?php echo $themeHelper->getProductLabel($_product) ?>
		
		<?php // Product Action ?>
		<ul class="actions-link">
		
			<?php // QuickView  ?>
			<li class="hidden-sm hidden-xs">
				<?php $quickViewHelper = $this->helper('MGS\QuickView\Helper\Data'); ?>
				<?php echo $quickViewHelper->aroundQuickViewHtml($_product); ?>
			</li>
			
			<?php // Wishlist  ?>
			<?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow() && !$themeSettings['catalog']['wishlist_button']): ?>
				<li>
					<button class="action towishlist"
					   title="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
					   data-title="<?php echo __('Add to Wish List') ?>"
					   aria-label="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
					   data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($_product); ?>'
					   data-action="add-to-wishlist"
					   role="button">
						<i class="fa fa-heart"></i>
					</button>
				</li>
			<?php endif; ?>
			
			<?php // Compare  ?>
			<?php $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare'); ?>
			<?php if(!$themeSettings['catalog']['compare_button']): ?>
				<li>
					<button class="action tocompare"
					   title="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
					   data-title="<?php echo __('Add to Compare') ?>"
					   aria-label="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
					   data-post='<?php /* @escapeNotVerified */ echo $compareHelper->getPostDataParams($_product); ?>'
					   role="button">
						<i class="fa fa-retweet"></i>
					</button>
				</li>
			<?php endif ?>
			
			<?php // Add to cart  ?>
			<?php if ($_product->isSaleable()): ?>
				<li>
					<?php $postParams = $block->getAddToCartPostParams($_product); ?>
					<?php $postParams = $block->getAddToCartPostParams($_product); ?>
				<form data-role="tocart-form" action="<?php /* @escapeNotVerified */ echo $this->getUrl('checkout/cart/add', ['uenc'=>$postParams['data']['uenc'], 'product'=>$postParams['data']['product']]); ?>" method="post">
					<input type="hidden" name="product" value="<?php /* @escapeNotVerified */ echo $postParams['data']['product']; ?>">
					<input type="hidden" name="uenc" value="<?php /* @escapeNotVerified */ echo $postParams['data']['uenc']; ?>">
					<input name="form_key" type="hidden" value="<?php echo $this->getFormKey() ?>" />
						<button class="action tocart btn-cart" type="submit" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
							<span class="fa fa-shopping-cart"></span>
						</button>
					</form>
				</li>
			<?php endif ?>
		</ul>
	</div>
	
	<?php // Product Detail ?>
	<div class="abc2 product details product-item-details">
		<?php 
		$_getbrand = $_product->getResource()->getAttribute('mgs_brand'); 
		$_getbrandValue = $_getbrand->getFrontend()->getValue($_product);
		?>
		<h5 class="designer_name product-item-name text-uppercase">
				<?php echo $_getbrandValue; ?>
			</h5>
		<?php // Product Name ?>
		<?php if ($_url_with_color){ ?>
		<h5 class="product name product-item-name">
			<a class="product-item-link"
			   href="<?php /* @escapeNotVerified */ echo $_url_with_color; ?>">
				<?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
			</a>
		</h5>
		<?php }else{ ?>
		<h5 class="product name product-item-name">
			<a class="product-item-link"
			   href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>">
				<?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
			</a>
		</h5>
		<?php } ?>
		
		
		<?php // Swatches Product ?>
		<?php echo $this->getLayout()->createBlock('Magento\Swatches\Block\Product\Renderer\Listing\Configurable')->setProduct($_product)->setTemplate('Magento_Swatches::product/listing/renderer.phtml')->toHtml() ?>
		
		<?php // Price ?>
		<?php /* @escapeNotVerified */ echo $block->getProductPrice($_product) ?>
		<?php if ($_product->isSaleable()): ?>
				<?php if ($_url_with_color){ ?>
				<div class="custom_addto_cart">
				<button type="button"
							title="<?php echo $block->escapeHtml(__('Add to Bag')); ?>"
							class="action tocart">

							<a href="<?php echo $_url_with_color; ?>"><?php echo $block->escapeHtml(__('Add to Bag')); ?>
							</a>
				</button>
				</div>
				<?php }else{ ?>
				<?php $postParams = $block->getAddToCartPostParams($_product); ?>
				<?php $postParams = $block->getAddToCartPostParams($_product); ?>
				<div class="custom_addto_cart">
				<form data-role="tocart-form" action="<?php /* @escapeNotVerified */ echo $this->getUrl('checkout/cart/add', ['uenc'=>$postParams['data']['uenc'], 'product'=>$postParams['data']['product']]); ?>" method="post">
					<input type="hidden" name="product" value="<?php /* @escapeNotVerified */ echo $postParams['data']['product']; ?>">
					<input type="hidden" name="uenc" value="<?php /* @escapeNotVerified */ echo $postParams['data']['uenc']; ?>">
					<input name="form_key" type="hidden" value="<?php echo $this->getFormKey() ?>" />
						<button class="action tocart btn-cart" type="submit" title="<?php /* @escapeNotVerified */ echo __('Add to Bag') ?>">
							Add to Bag
						</button>
					</form>
				</div>
				<?php } ?>


			<?php endif ?>
	</div>
</div>