<?php
/**
 * Copyright Â© 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
?>
<?php
$_productCollection = $block->getLoadedProductCollection();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$themeHelper = $this->helper('MGS\Mpanel\Helper\Data');

$lazyLoad = $themeHelper->getStoreConfig('mgstheme/general/lazy_load');
$baseImage = $this->getViewFileUrl('MGS_Mpanel::images/blank.png');

$colClassRow = $themeHelper->getColClass();
$arrColClass = explode(' ', $colClassRow);
$pageType = 'catalog';
$settings = $themeHelper->getThemeSettings();
$perrow = $settings['catalog']['per_row'];
if($this->hasData('page_type')){
	$pageType = $this->getData('page_type');
}
if($pageType == 'catalog'){
	$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
	$category = $objectManager->get('Magento\Framework\Registry')->registry('current_category');
	if($category->getPerRow()){
		$perrow = $category->getPerRow();
	}
}elseif($pageType == 'catalogsearch') {
	if($settings['catalogsearch']['per_row']){
		$perrow = $settings['catalogsearch']['per_row'];
	}
}elseif($pageType == 'catalog_brand') {
	if($settings['catalog_brand']['per_row']){
		$perrow = $settings['catalog_brand']['per_row'];
	}
}

$colCheck = $themeHelper->convertPerRowtoCol($perrow);
$colClass = $themeHelper->convertColClass($colCheck, 'col');
?>
<?php if (!$_productCollection->count()): ?>
    <div class="message info empty"><div><?php /* @escapeNotVerified */ echo __('We can\'t find products matching the selection.') ?></div></div>
<?php else: ?>
	<div class="category-product-actions">
		<?php echo $block->getToolbarHtml() ?>
		<?php echo $block->getAdditionalHtml() ?>
	</div>
    <?php
    if ($block->getMode() == 'grid') {
        $viewMode = 'grid';
        $image = 'category_page_grid';
		$image_hover = 'product_base_image';
		$_imageHover = 'hover_product_list';
        $showDescription = false;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    } else {
        $viewMode = 'list';
        $image = 'category_page_list';
		$image_hover = 'product_base_image';
		$_imageHover = 'hover_product_list';
        $showDescription = true;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    }
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    ?>
    <?php $_url_with_color = ''; $_parent_product = []; $_parproduct = '';?>
    <div class="products wrapper <?php /* @escapeNotVerified */ echo $viewMode; ?> products-<?php /* @escapeNotVerified */ echo $viewMode; ?>" id="product-wrapper">
        <?php $iterator = 1; ?>
        <ol class="products list items product-items <?php if ($block->getMode() == 'grid'): ?>row<?php endif ?> <?php echo 'row-'.$arrColClass[0] ?>">
		
			<?php $_imagehelper = $this->helper('Magento\Catalog\Helper\Image'); ?>
			<?php $size = $themeHelper->getImageSize(); ?>
			<?php $quickViewHelper = $this->helper('MGS\QuickView\Helper\Data'); ?>
			<?php $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare'); ?>
			
			<?php if ($block->getMode() == 'grid'): ?>
				<?php $params = $block->getRequest()->getParams();  ?>
				<?php if($settings['catalog']['ajaxscroll']): ?>
				
					<?php if(isset($params['product_list_limit'])): ?>
						<?php $countAll = $params['product_list_limit']; ?>
					<?php else: ?>
						<?php $countAll = $themeHelper->getStoreConfig('catalog/frontend/grid_per_page'); ?>		
					<?php endif ?>
					
					<?php if(isset($params['p'])): ?>
						<?php $i = ($params['p'] - 1) * $countAll; ?>
					<?php else: ?>
						<?php $i = 0; ?>
					<?php endif ?>
					
				<?php else: ?>
					<?php $i = 0; ?>
				<?php endif ?>
				
				<?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
				<?php
				$_objectManager = \Magento\Framework\App\ObjectManager::getInstance();
				$this->scopeConfig = $_objectManager->create('\Magento\Framework\App\Config\ScopeConfigInterface');
				$baseUrl =  $_objectManager->get('Magento\Store\Model\StoreManagerInterface')
                ->getStore()
                ->getBaseUrl();
				
				foreach ($_productCollection as $_product): $i++;
						$repository = $_objectManager->create('Magento\Catalog\Model\ProductRepository');
						// $pr = $repository->get($_product->getSku());
						$_parent_product = $_objectManager->create('Magento\ConfigurableProduct\Model\ResourceModel\Product\Type\Configurable')->getParentIdsByChild($_product->getEntityId());

							if(!empty($_parent_product[0])){ 
								$_parproduct = $_objectManager->get('Magento\Catalog\Model\Product')->load($_parent_product[0]);
								$productUrlKey = $_parproduct->getUrlKey();
								$productSuffix = $this->scopeConfig->getValue('catalog/seo/product_url_suffix', \Magento\Store\Model\ScopeInterface::SCOPE_STORE);
								$productUrl = $baseUrl . $productUrlKey . $productSuffix;

								$getcolor = $_product->getResource()->getAttribute('color'); 
								$getcolorValue = $getcolor->getFrontend()->getValue($_product);
								$_url_with_color = $productUrl."?color=".$getcolorValue;
							}else{
								$_url_with_color = '';
								$_parent_product = [];
								$_parproduct = '';
							}		
				?>
					<li class="item product product-item-info product-item <?php echo $colClass ?> <?php echo $themeHelper->getClearClass($perrow, $i) ?>">
						<?php $_productNameStripped = $block->stripTags($_product->getName(), null, true); ?>
						<?php $productImage = $_imagehelper->init($_product, $image)->resize($size['width'], $size['height'])->getUrl(); ?>
						<?php if(!$lazyLoad){
							$baseImage = $productImage;
						} ?>
						<div class="product-top">
							<?php if ($_url_with_color){ ?>
								<a href="<?php echo $_url_with_color; ?>" class="product photo product-item-photo" tabindex="-1">
							<?php }else{ ?>
								<a href="<?php echo $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
							<?php } ?>	

								<img src="<?php echo $baseImage; ?>" alt="<?php echo $_productNameStripped ?>" class="img-responsive <?php 
							if($_product->getData('hover') == 'no_selection' || $_product->getData('hover') == ''){
							}else{ ?>img-hover-1<?php } ?> product-image-photo img-thumbnail<?php if($lazyLoad): ?> lazy<?php endif ?>" data-original="<?php echo $productImage; ?>"/>
								<?php 
							if($_product->getData('hover') == 'no_selection' || $_product->getData('hover') == ''){
								}else{ ?>
								<?php 
								$imageHoverUrl = $_imagehelper->init($_product, $_imageHover)
								->resize($size['width'], $size['height'])->getUrl(); ?>
								<img src="<?php echo $imageHoverUrl; ?>" alt="<?php echo $_productNameStripped ?>" class="img-responsive product-image-photo img-thumbnail img-hover<?php if($lazyLoad): ?> lazy<?php endif ?>" data-original="<?php echo $imageHoverUrl; ?>"/>
							<?php } ?>
							</a>
							<?php echo $themeHelper->getProductLabel($_product) ?>
							<ul class="actions-link" data-role="add-to-links">
							
								<li class="hidden-sm hidden-xs"><?php echo $quickViewHelper->aroundQuickViewHtml($_product); ?></li>
								
								<?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow() && !$settings['catalog']['wishlist_button']): ?>
									<li><button data-title="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
									   class="action towishlist"
									   title="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
									   aria-label="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
									   data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($_product); ?>'
									   data-action="add-to-wishlist"
									   role="button">
										<i class="fa fa-heart"></i>
									</button></li>
								<?php endif; ?>
									
								<?php if(!$settings['catalog']['compare_button']): ?>
									<li><button data-title="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
									   class="action tocompare"
									   title="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
									   aria-label="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
									   data-post='<?php /* @escapeNotVerified */ echo $compareHelper->getPostDataParams($_product); ?>'
									   role="button">
										<i class="fa fa-retweet"></i>
									</button></li>
								<?php endif ?>
								
								
							</ul>
						</div>
						<div class="product details product-item-details">
							<?php 
							$_getbrand = $_product->getResource()->getAttribute('mgs_brand'); // 
							$_getbrandValue = $_getbrand->getFrontend()->getValue($_product);
							// if($_getbrandValue){
							?>
							<h5 class="designer_name product-item-name text-uppercase">
								<?php echo $_getbrandValue; ?>
							</h5>
							<?php //} ?>
							<?php if ($_url_with_color){ ?>
								<h5 class="product name product-item-name">
								<a class="product-item-link" href="<?php echo $_url_with_color; ?>">
									<?php echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
								</a>
							</h5>
							<?php }else{ ?>
								<h5 class="product name product-item-name">
								<a class="product-item-link" href="<?php echo $_product->getProductUrl() ?>">
									<?php echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
								</a>
							</h5>
							<?php } ?>	

							<?php echo $block->getProductDetailsHtml($_product); ?>
							
							<?php echo $block->getProductPrice($_product) ?>
							<?php if ($_product->isSaleable()): ?>
							<div class="custom_addto_cart">
								<?php 
								
								// $parent_product = $_objectManager->create('Magento\ConfigurableProduct\Model\ResourceModel\Product\Type\Configurable')->getParentIdsByChild($_product->getEntityId());
								if ($_parent_product){ 
									// $parproduct = $_objectManager->get('Magento\Catalog\Model\Product')->load($_parent_product[0]);
									$_getcolor = $_product->getResource()->getAttribute('color'); // 
									$_getcolorValue = $_getcolor->getFrontend()->getValue($_product);
								?>
								<button type="button"
												title="<?php echo $block->escapeHtml(__('Add to Bag')); ?>"
												class="action tocart">

												<a href="<?php echo $_parproduct->getProductUrl().'?color='.$_getcolorValue; ?>"><?php echo $block->escapeHtml(__('Add to Bag')); ?>
												</a>
								</button>
							     
							<?php } else if($_product->getTypeId() == \Magento\ConfigurableProduct\Model\Product\Type\Configurable::TYPE_CODE){ ?>
								<button type="button" title="<?php echo $block->escapeHtml(__('Add to Bag')); ?>" class="action tocart">
									<a href="<?php echo $_product->getProductUrl() ?>"><?php echo $block->escapeHtml(__('Add to Bag')); ?>
									</a>
								</button>
							<?php } else { ?>	
								<?php /*$postParams = $block->getAddToCartPostParams($_product);*/ ?>
								<?php $postParams = $block->getAddToCartPostParams($_product); ?>
								<form data-role="tocart-form" action="<?php /* @escapeNotVerified */ echo $this->getUrl('checkout/cart/add', ['uenc'=>$postParams['data'][Action::PARAM_NAME_URL_ENCODED], 'product'=>$postParams['data']['product']]); ?>" method="post">
									<input type="hidden" name="product" value="<?php /* @escapeNotVerified */ echo $postParams['data']['product']; ?>">
									<input type="hidden" name="<?php /* @escapeNotVerified */ echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php /* @escapeNotVerified */ echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
									<?php echo $block->getBlockHtml('formkey')?>
									<button type="submit"
											title="<?php echo $block->escapeHtml(__('Add to Bag')); ?>"
											class="action tocart">
											<?php echo $block->escapeHtml(__('Add to Bag')); ?>
									</button>
								</form>
							<?php } ?>
							</div>
							<?php else: ?>
								<div class="custom_addto_cart">
									<div class="stock unavailable" title="Availability" style="color:red;">
							            <span>Out of stock</span>
							        </div>
								</div>
							<?php endif ?>
							

								
						</div>
					</li>
				<?php endforeach ?>
			<?php else: ?>
				<?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
				<?php foreach ($_productCollection as $_product): ?>
					<?php $_productNameStripped = $block->stripTags($_product->getName(), null, true); ?>
					<?php $productImage = $_imagehelper->init($_product, $image)->resize($size['width'], $size['height'])->getUrl(); ?>
					<?php if(!$lazyLoad){
						$baseImage = $productImage;
					} ?>
					<li class="item product product-item-info product-item">
						<div class="row">
							<div class="col-md-3 col-sm-4 col-xs-12">
								<div class="product-image-content">
									<a href="<?php echo $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
										<img src="<?php echo $baseImage; ?>" alt="<?php echo $_productNameStripped ?>" class="img-responsive product-image-photo img-thumbnail<?php if($lazyLoad): ?> lazy<?php endif ?>" data-original="<?php echo $productImage; ?>"/>
									</a>
									<?php echo $themeHelper->getProductLabel($_product) ?>
								</div>
							</div>
							<div class="col-md-9 col-sm-8 col-xs-12">
								<div class="product details product-item-details">
								
									<h5 class="product name product-item-name">
										<a class="product-item-link" href="<?php echo $_product->getProductUrl() ?>">
											<?php echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
										</a>
									</h5>
									
									<?php echo $block->getReviewsSummaryHtml($_product, $templateType,true); ?>
									
									<?php echo $block->getProductDetailsHtml($_product); ?>
									
									<?php echo $block->getProductPrice($_product) ?>
									
									<div class="product description product-item-description">
										<?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
										<a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" title="<?php /* @escapeNotVerified */ echo $_productNameStripped ?>"
										   class="action more"><?php /* @escapeNotVerified */ echo __('Learn More') ?></a>
									</div>
									
									<ul class="actions-link" data-role="add-to-links">
									
										<?php if ($_product->isSaleable()): ?>
											<li><?php $postParams = $block->getAddToCartPostParams($_product); ?>
											<form data-role="tocart-form" action="<?php /* @escapeNotVerified */ echo $postParams['action']; ?>" method="post">
												<input type="hidden" name="product" value="<?php /* @escapeNotVerified */ echo $postParams['data']['product']; ?>">
												<input type="hidden" name="<?php /* @escapeNotVerified */ echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php /* @escapeNotVerified */ echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
												<?php echo $block->getBlockHtml('formkey')?>
												<button type="submit"
														title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>"
														class="action tocart">
													<span class="fa fa-shopping-cart"></span><span><?php echo $block->escapeHtml(__('Add To Cart')); ?></span>
												</button>
											</form></li>
										<?php endif ?>
										
										<?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow() && !$settings['catalog']['wishlist_button']): ?>
											<li><button data-title="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
											   class="action towishlist"
											   title="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
											   aria-label="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
											   data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($_product); ?>'
											   data-action="add-to-wishlist"
											   role="button">
												<i class="fa fa-heart"></i>
											</button></li>
										<?php endif; ?>
											
										<?php if(!$settings['catalog']['compare_button']): ?>
											<li><button data-title="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
											   class="action tocompare"
											   title="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
											   aria-label="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
											   data-post='<?php /* @escapeNotVerified */ echo $compareHelper->getPostDataParams($_product); ?>'
											   role="button">
												<i class="fa fa-retweet"></i>
											</button></li>
										<?php endif ?>
										
										<li class="hidden-sm hidden-xs"><?php echo $quickViewHelper->aroundQuickViewHtml($_product); ?></li>
										
									</ul>
								</div>
							</div>
						</div>
					</li>
				<?php endforeach ?>
			<?php endif ?>
        </ol>
    </div>
	<div class="bottom-pagination<?php if($themeHelper->getStoreConfig('mpanel/catalog/ajaxscroll')): ?> ajaxscroll-enable<?php endif ?>">
		<?php echo $block->getToolbarHtml() ?>
	</div>
    <?php if (!$block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {}
            }
        }
        </script>
    <?php endif; ?>
<?php endif; ?>
