<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Category view template
 *
 * @var $block \Magento\Catalog\Block\Category\View
 */
?>
<?php /*if ($_description = $block->getCurrentCategory()->getDescription()):
	$_category  = $block->getCurrentCategory();
	$parentCategoryObj = $_category->getParentCategory($_category->getId());
    if($parentCategoryObj->getName() != 'Designers' || $parentCategoryObj->getUrlKey() != 'designers'):
 ?>
    <div class="category-description">
        <?php /* @escapeNotVerified */ /*echo $this->helper('Magento\Catalog\Helper\Output')->categoryAttribute($block->getCurrentCategory(), $_description, 'description') ?>
    </div>
<?php endif; endif; */ ?>
